"""Build the GitBook site output into site/.

Generators write directly into site/ so that docs/api/guardrails/ (which
contains mkdocstrings stubs) never enters the GitBook output.

Navigation is read from docs/SUMMARY.md — edit that file to add or rename
pages; no changes to this script are needed.

The contents of site/ are pushed to the gitbook-docs branch by CI.

Usage:
    python scripts/convert_to_gitbook.py
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
DOCS_SRC = Path("docs")
SITE_DIR = Path("site")

# Static asset directories to copy verbatim
ASSET_DIRS = ["images", "assets"]


def copy_static_docs() -> None:
    """Copy top-level Markdown from docs/ into site/.

    Excludes api/ — those pages are fully generated by generate_api_docs.py
    and written directly into site/api/ to avoid the mkdocstrings stubs in
    docs/api/ from overwriting them.
    """
    for src in sorted(DOCS_SRC.glob("*.md")):
        dst = SITE_DIR / src.name
        shutil.copy2(src, dst)


def copy_assets() -> None:
    """Copy static asset directories from docs/ into site/."""
    for subdir in ASSET_DIRS:
        src = DOCS_SRC / subdir
        if src.exists():
            shutil.copytree(src, SITE_DIR / subdir)
            print(f"  Copied {len(list(src.rglob('*')))} assets from docs/{subdir}/")


def validate_summary(summary: str, site_dir: Path) -> None:
    """Assert every page listed in SUMMARY.md exists under site/."""
    missing = []
    for line in summary.splitlines():
        if "(" not in line or ")" not in line:
            continue
        start = line.index("(") + 1
        end = line.index(")", start)
        path = line[start:end].strip()
        if not path or path.startswith("http"):
            continue
        if not (site_dir / path).exists():
            missing.append(path)

    if missing:
        print("ERROR: the following SUMMARY.md pages are missing from site/:", file=sys.stderr)
        for p in missing:
            print(f"  {p}", file=sys.stderr)
        sys.exit(1)


def main() -> None:
    """Build the GitBook-flavored Markdown site into ``site/``."""
    # Create site/ fresh
    if SITE_DIR.exists():
        shutil.rmtree(SITE_DIR)
    SITE_DIR.mkdir()

    # Generate API docs directly into site/api/ (bypasses docs/api/guardrails/ stubs)
    print("Generating API docs...")
    sys.path.insert(0, str(SCRIPT_DIR))
    import generate_api_docs

    generate_api_docs.main(SITE_DIR / "api")

    # Generate cookbooks directly into site/cookbook/
    print("Converting cookbooks...")
    import generate_cookbooks

    generate_cookbooks.main(SITE_DIR / "cookbook")

    # Copy hand-written docs and assets
    print("Copying static docs...")
    copy_static_docs()
    copy_assets()

    # SUMMARY.md lives in docs/ — copy it to site/ as the authoritative navigation
    summary_src = DOCS_SRC / "SUMMARY.md"
    summary_text = summary_src.read_text(encoding="utf-8")
    shutil.copy2(summary_src, SITE_DIR / "SUMMARY.md")

    # Copy GitBook config
    gitbook_yaml = Path(".gitbook.yaml")
    if gitbook_yaml.exists():
        shutil.copy2(gitbook_yaml, SITE_DIR / ".gitbook.yaml")

    # Validate before finishing
    print("Validating SUMMARY.md...")
    validate_summary(summary_text, SITE_DIR)

    md_count = len(list(SITE_DIR.rglob("*.md")))
    print(f"\nDone — {md_count} Markdown files written to {SITE_DIR}/")


if __name__ == "__main__":
    main()
