"""Generate the grouped guardrail navigation block in ``docs/SUMMARY.md``.

``docs/SUMMARY.md`` is the committed, human-reviewed GitBook table of contents
(``scripts/convert_to_gitbook.py`` copies it verbatim and validates every link).
Rather than hand-maintain the alphabetical guardrail list, the region between the
``GUARDRAIL-NAV`` markers is generated from the taxonomy registry: each guardrail
is listed once under its ``primary_category`` (categories in enum-declaration
order, guardrails sorted by ``display_name``).

This keeps navigation in sync with ``GUARDRAIL_METADATA`` — adding a guardrail
updates the nav automatically — while leaving the rest of ``SUMMARY.md`` under
manual control. Wired into pre-commit with ``--check`` so CI fails if the
committed file has drifted.

Usage:
    python scripts/generate_summary.py            # rewrite the nav block in docs/SUMMARY.md
    python scripts/generate_summary.py --check    # exit non-zero if the block is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Ensure the package is importable when run directly.
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from any_guardrail.base import GuardrailName
from any_guardrail.registry import GUARDRAIL_METADATA
from any_guardrail.taxonomy import GuardrailCategory

DEFAULT_SUMMARY = Path(__file__).parent.parent / "docs" / "SUMMARY.md"

START_MARKER = "<!-- GUARDRAIL-NAV:START — generated by scripts/generate_summary.py; do not edit by hand -->"
END_MARKER = "<!-- GUARDRAIL-NAV:END -->"

# Human-facing section titles for each category (declaration order = section order).
CATEGORY_TITLES: dict[GuardrailCategory, str] = {
    GuardrailCategory.PROMPT_INJECTION: "Prompt Injection",
    GuardrailCategory.CONTENT_SAFETY: "Content Safety",
    GuardrailCategory.TOXICITY: "Toxicity",
    GuardrailCategory.PII: "PII",
    GuardrailCategory.HALLUCINATION: "Hallucination",
    GuardrailCategory.OFF_TOPIC: "Off-Topic",
    GuardrailCategory.BIAS: "Bias",
    GuardrailCategory.TOOL_USE: "Tool Use",
    GuardrailCategory.GENERAL_JUDGE: "General Judge",
}

# Indentation of the generated lines under the "* [Guardrails](...)" tree node.
_SECTION_INDENT = "  "
_ITEM_INDENT = "    "


def _page(name: GuardrailName) -> str:
    return f"api/guardrails/{name.value.replace('_', '-')}.md"


def build_nav() -> str:
    """Build the marker-delimited nav block (grouped by primary category)."""
    by_primary: dict[GuardrailCategory, list[GuardrailName]] = {}
    for name in GuardrailName:
        by_primary.setdefault(GUARDRAIL_METADATA[name].primary_category, []).append(name)

    lines = [f"{_SECTION_INDENT}{START_MARKER}"]
    for category, title in CATEGORY_TITLES.items():
        names = by_primary.get(category, [])
        if not names:
            continue
        lines.append(f"{_SECTION_INDENT}* {title}")
        for name in sorted(names, key=lambda n: GUARDRAIL_METADATA[n].display_name.lower()):
            display = GUARDRAIL_METADATA[name].display_name
            lines.append(f"{_ITEM_INDENT}* [{display}]({_page(name)})")
    lines.append(f"{_SECTION_INDENT}{END_MARKER}")
    return "\n".join(lines)


def render(summary_text: str) -> str:
    """Return ``summary_text`` with the nav block between the markers replaced."""
    start = summary_text.index(START_MARKER)
    end = summary_text.index(END_MARKER) + len(END_MARKER)
    # Back up to the start of the marker's line (drop its leading indentation too).
    line_start = summary_text.rfind("\n", 0, start) + 1
    return summary_text[:line_start] + build_nav() + summary_text[end:]


def main() -> int:
    """Generate or check the guardrail navigation block in SUMMARY.md."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_SUMMARY, help=f"SUMMARY path (default: {DEFAULT_SUMMARY})")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero (without writing) if the committed nav block is stale.",
    )
    args = parser.parse_args()

    current = args.out.read_text(encoding="utf-8")
    if START_MARKER not in current or END_MARKER not in current:
        print(
            f"{args.out} is missing the GUARDRAIL-NAV markers; add them under the Guardrails node.",
            file=sys.stderr,
        )
        return 1

    updated = render(current)

    if args.check:
        if current != updated:
            print(
                f"{args.out} guardrail nav is out of date. Run `python scripts/generate_summary.py` and commit.",
                file=sys.stderr,
            )
            return 1
        return 0

    args.out.write_text(updated, encoding="utf-8")
    print(f"Updated {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
