"""Generate a browsable catalog of every guardrail's default prompt and authored content.

Renders ``docs/prompt_catalog.md`` — each guardrail's default prompt template text plus its
author-published policies / rubrics / criteria, from the import-free ``PROMPT_REGISTRY`` and
``CONTENT_REGISTRY`` (so it never drifts). Committed and viewable on GitHub + the docs site; wired
into pre-commit with ``--check``.

Usage:
    python scripts/generate_prompt_catalog.py            # write docs/prompt_catalog.md
    python scripts/generate_prompt_catalog.py --check    # exit non-zero if the committed file is stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from any_guardrail.content import ContentKind
from any_guardrail.content_registry import CONTENT_REGISTRY
from any_guardrail.prompt_registry import PROMPT_REGISTRY
from any_guardrail.registry import GUARDRAIL_METADATA

DEFAULT_OUT = Path(__file__).parent.parent / "docs" / "prompt_catalog.md"


def _fence(text: str) -> str:
    """Wrap ``text`` in a ``text`` code fence long enough to contain any backticks inside it."""
    longest = max((len(m) for m in re.findall(r"`+", text)), default=0)
    ticks = "`" * max(3, longest + 1)
    return f"{ticks}text\n{text}\n{ticks}"


def build() -> str:
    """Render the catalog markdown from the prompt + content registries."""
    lines = [
        "# Prompt & content catalog",
        "",
        "<!-- Generated by scripts/generate_prompt_catalog.py — do not edit by hand. -->",
        "",
        "The default prompt template and any author-published policies / rubrics / criteria for each",
        "guardrail. See [Prompts & content](prompts.md) for how to fetch, version, and override them.",
        "",
    ]
    names = sorted(
        set(PROMPT_REGISTRY) | set(CONTENT_REGISTRY),
        key=lambda n: GUARDRAIL_METADATA[n].display_name.lower(),
    )
    for name in names:
        lines += [f"## {GUARDRAIL_METADATA[name].display_name}", ""]
        spec = PROMPT_REGISTRY.get(name)
        if spec is not None:
            for version, template in spec.versions.items():
                tags = [f"`{template.assembly.value}`", template.provenance]
                if not template.overridable:
                    tags.append("reference-only")
                header = f"**Prompt** (`{version}`) — {' · '.join(tags)}"
                if template.source:
                    header += f" · [source]({template.source})"
                lines += [header, ""]
                for segment_name, segment in template.segments.items():
                    lines += [f"*{segment_name}:*", "", _fence(segment), ""]
        items = CONTENT_REGISTRY.get(name)
        if items:
            for kind in (ContentKind.POLICY, ContentKind.RUBRIC, ContentKind.CRITERIA):
                by_kind = sorted((c for c in items if c.kind == kind), key=lambda c: c.key)
                if not by_kind:
                    continue
                lines += [f"**{kind.value.capitalize()}:**", ""]
                for content in by_kind:
                    lines += [
                        f"<details><summary><code>{content.key}</code></summary>",
                        "",
                        _fence(content.content),
                        "",
                        "</details>",
                        "",
                    ]
    # Strip trailing whitespace per line (prompt text can carry trailing spaces) so the committed
    # file matches what the trim-trailing-whitespace pre-commit hook would leave.
    text = "\n".join(lines)
    return "\n".join(line.rstrip() for line in text.split("\n")).rstrip() + "\n"


def main() -> int:
    """Generate or check the committed prompt catalog."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help=f"Output path (default: {DEFAULT_OUT})")
    parser.add_argument("--check", action="store_true", help="Exit non-zero if the committed file is stale.")
    args = parser.parse_args()

    content = build()
    if args.check:
        if not args.out.exists() or args.out.read_text(encoding="utf-8") != content:
            print(
                f"{args.out} is out of date. Run `python scripts/generate_prompt_catalog.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        return 0

    args.out.write_text(content, encoding="utf-8")
    print(f"Wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
