# ruff: noqa: E501
"""Verbatim flow_judge default judge-prompt templates, mirrored for the import-free prompt registry.

Generated from ``flow_judge.utils.prompt_formatter`` (v0.1.2). This module holds only string
constants (stdlib-only) so the prompt registry can expose Flowjudge's default prompt without
importing the ``flow_judge`` library. Kept byte-identical to the installed library by
``tests/unit/test_prompts.py::test_flowjudge_reference_matches_library`` (skipped without the
flowjudge extra). E501 is disabled here because the upstream template has long prose lines."""

USER_PROMPT_TEMPLATE = '# GOAL\nYour job is to evaluate a task carried out by an AI system powered by a large language model.\n\nYou will be provided with the inputs and output of the task, as well as the evaluation criteria and scoring rubric. Your task is to evaluate the output of the AI system based on the evaluation criteria and scoring rubric provided.\n\n# INPUT\nBelow are the inputs required for performing the task:\n<inputs>\n{INPUTS}\n</inputs>\n\n# OUTPUT\nBelow is the output of the task:\n<output>\n{OUTPUT}\n</output>\n\n# EVALUATION CRITERIA AND SCORING RUBRIC\nHere are the evaluation criteria and the rubric that you need to use for evaluating the task:\n<evaluation_criteria>\n{EVALUATION_CRITERIA}\n</evaluation_criteria>\n\n<scoring_rubric>\n{RUBRIC}\n</scoring_rubric>\n\n# INSTRUCTIONS FOR THE EVALUATION\n1. Understand the task and criteria: Familiarize yourself with the task to be evaluated. Review the evaluation criteria and scoring rubric to understand the different levels of performance and the descriptions for each score.\n2. Review the inputs and output: Look at the inputs provided for the task. Examine the output generated from completing the task.\n3. Compare output to score descriptions: Compare the output against the criteria and score descriptions in the scoring rubric. For each criterion,decide which description best matches the output.\n4. After comparing the output to the score descriptions, pay attention to the small details that might impact the final score that you assign. Sometimes a small difference can dictate the final score.\n5. Write verbal feedback justifying your evaluation that includes a detailed rationale, referring to specific aspects of the output and comparing them to the rubric.\n6. Assign a final score based on the scoring rubric.\n\n## FORMAT FOR THE EVALUATION\n- Write the verbal feedback inside <feedback> tags without any additional surrounding text.\n- Write the numeric score inside <score> tags, without any additional surrounding text and always after the feedback.\n\nPlease accurately evaluate the task. Strictly adhere to the evaluation criteria and rubric.'

USER_PROMPT_NO_INPUTS_TEMPLATE = '# GOAL\nYour job is to evaluate a task carried out by an AI system powered by a large language model.\n\nYou will be provided the output of the task, as well as the evaluation criteria and scoring rubric. Your task is to evaluate the output of the AI system based on the evaluation criteria and scoring rubric provided.\n\n# OUTPUT\nBelow is the output of the task:\n<output>\n{OUTPUT}\n</output>\n\n# EVALUATION CRITERIA AND SCORING RUBRIC\nHere are the evaluation criteria and the rubric that you need to use for evaluating the task:\n<evaluation_criteria>\n{EVALUATION_CRITERIA}\n</evaluation_criteria>\n\n<scoring_rubric>\n{RUBRIC}\n</scoring_rubric>\n\n# INSTRUCTIONS FOR THE EVALUATION\n1. Understand the task and criteria: Familiarize yourself with the task to be evaluated. Review the evaluation criteria and scoring rubric to understand the different levels of performance and the descriptions for each score.\n2. Review the output: Examine the output generated from completing the task.\n3. Compare output to score descriptions: Compare the output against the criteria and score descriptions in the scoring rubric. For each criterion,decide which description best matches the output.\n4. After comparing the output to the score descriptions, pay attention to the small details that might impact the final score that you assign. Sometimes a small difference can dictate the final score.\n5. Write verbal feedback justifying your evaluation that includes a detailed rationale, referring to specific aspects of the output and comparing them to the rubric.\n6. Assign a final score based on the scoring rubric.\n\n## FORMAT FOR THE EVALUATION\n- Write the verbal feedback inside <feedback> tags without any additional surrounding text.\n- Write the numeric score inside <score> tags, without any additional surrounding text and always after the feedback.\n\nPlease accurately evaluate the task. Strictly adhere to the evaluation criteria and rubric.'
