"""Central, import-free registry of guardrail capability metadata.

This module is the single source of truth for guardrail taxonomy queries. It
imports only :mod:`any_guardrail.base` (for ``GuardrailName``) and
:mod:`any_guardrail.taxonomy` (leaf enums + model) — never a guardrail
implementation — so filtering/grouping never pulls in ``torch``/``transformers``
or spins up a backend. Each guardrail class mirrors its entry here as
``METADATA``; a parity test enforces that every ``GuardrailName`` has exactly one
entry and that the class ClassVar is that entry.

The ``description`` of each entry equals the guardrail class docstring's first
summary line (also test-enforced), so it doubles as the catalog flavor text.
"""

from any_guardrail.base import GuardrailName
from any_guardrail.taxonomy import (
    BackendType,
    GuardrailCategory,
    GuardrailMetadata,
    GuardrailStage,
    OutputShape,
    VariantLicense,
)

GUARDRAIL_METADATA: dict[GuardrailName, GuardrailMetadata] = {
    GuardrailName.ANYLLM: GuardrailMetadata(
        description="Policy-based LLM judge that grades text against a natural-language policy using an LLM provider.",
        display_name="AnyLlm",
        categories=frozenset({GuardrailCategory.GENERAL_JUDGE}),
        primary_category=GuardrailCategory.GENERAL_JUDGE,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.SCORE}),
        backend=BackendType.HOSTED_API,
        required_validate_kwargs=frozenset({"policy"}),
        optional_validate_kwargs=frozenset({"model_id", "system_prompt", "prompt_version"}),
        requires_api_key=True,
        vendor="Mozilla AI",
        default_license="apache-2.0",
    ),
    GuardrailName.BEDROCK_GUARDRAILS: GuardrailMetadata(
        description="Hosted, configurable moderation covering content filters, denied topics, PII, word filters, and contextual grounding.",
        display_name="Bedrock Guardrails",
        categories=frozenset(
            {
                GuardrailCategory.CONTENT_SAFETY,
                GuardrailCategory.PII,
                GuardrailCategory.OFF_TOPIC,
                GuardrailCategory.HALLUCINATION,
            }
        ),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT, GuardrailStage.RAG_CONTEXT}),
        output_shapes=frozenset({OutputShape.CATEGORICAL}),
        backend=BackendType.HOSTED_API,
        requires_api_key=True,
        multilingual=True,
        vendor="Amazon",
        default_license="proprietary",
    ),
    GuardrailName.DEEPSET: GuardrailMetadata(
        description="Binary prompt-injection classifier.",
        display_name="Deepset",
        categories=frozenset({GuardrailCategory.PROMPT_INJECTION}),
        primary_category=GuardrailCategory.PROMPT_INJECTION,
        stages=frozenset({GuardrailStage.INPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.SCORE}),
        backend=BackendType.LOCAL_ENCODER,
        vendor="deepset",
        default_license="mit",
    ),
    GuardrailName.DUOGUARD: GuardrailMetadata(
        description="Multilingual multi-label safety classifier scoring text across 12 harm categories including jailbreak prompts.",
        display_name="DuoGuard",
        categories=frozenset(
            {GuardrailCategory.CONTENT_SAFETY, GuardrailCategory.TOXICITY, GuardrailCategory.PROMPT_INJECTION}
        ),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.MULTI_LABEL, OutputShape.SCORE}),
        backend=BackendType.LOCAL_ENCODER,
        multilingual=True,
        vendor="DuoGuard",
        # Default (0.5B) and 1.5B are Apache-2.0 (Qwen2.5 base); the 1B transfer carries Llama 3.2 terms.
        default_license="apache-2.0",
        variant_licenses=(
            VariantLicense(model_id="DuoGuard/DuoGuard-0.5B", license="apache-2.0"),
            VariantLicense(model_id="DuoGuard/DuoGuard-1B-Llama-3.2-transfer", license="llama-3.2"),
            VariantLicense(model_id="DuoGuard/DuoGuard-1.5B-transfer", license="apache-2.0"),
        ),
    ),
    GuardrailName.FLOWJUDGE: GuardrailMetadata(
        description="Local LLM judge scoring text against user-defined criteria, metrics, and rubrics.",
        display_name="Flow Judge",
        categories=frozenset({GuardrailCategory.GENERAL_JUDGE}),
        primary_category=GuardrailCategory.GENERAL_JUDGE,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.RUBRIC}),
        backend=BackendType.LIBRARY_WRAPPED,
        required_validate_kwargs=frozenset({"output"}),
        vendor="Flow AI",
        default_license="apache-2.0",
    ),
    GuardrailName.GLIDER: GuardrailMetadata(
        description="Prompt-based LLM judge that grades text against user-supplied pass criteria and rubric, returning reasoning and highlighted phrases.",
        display_name="GLIDER",
        categories=frozenset({GuardrailCategory.GENERAL_JUDGE}),
        primary_category=GuardrailCategory.GENERAL_JUDGE,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.RUBRIC}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        vendor="Patronus AI",
        default_license="cc-by-nc-4.0",
    ),
    GuardrailName.GRANITE_GUARDIAN: GuardrailMetadata(
        description="Hybrid-thinking safety and judge model covering harm, RAG groundedness, and function-calling risks via bring-your-own-criteria.",
        display_name="Granite Guardian",
        categories=frozenset(
            {
                GuardrailCategory.GENERAL_JUDGE,
                GuardrailCategory.CONTENT_SAFETY,
                GuardrailCategory.HALLUCINATION,
                GuardrailCategory.BIAS,
                GuardrailCategory.TOOL_USE,
                GuardrailCategory.PROMPT_INJECTION,
            }
        ),
        primary_category=GuardrailCategory.GENERAL_JUDGE,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT, GuardrailStage.RAG_CONTEXT}),
        output_shapes=frozenset({OutputShape.CATEGORICAL, OutputShape.SCORE}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"available_tools", "documents", "output_text"}),
        vendor="IBM",
        default_license="apache-2.0",
    ),
    GuardrailName.HARMGUARD: GuardrailMetadata(
        description="Binary safety and jailbreak classifier, scoring a prompt or prompt-response pair.",
        display_name="HarmAug-Guard",
        categories=frozenset({GuardrailCategory.PROMPT_INJECTION, GuardrailCategory.CONTENT_SAFETY}),
        primary_category=GuardrailCategory.PROMPT_INJECTION,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.SCORE}),
        backend=BackendType.LOCAL_ENCODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        vendor="hbseong",
        default_license="apache-2.0",
    ),
    GuardrailName.INJECGUARD: GuardrailMetadata(
        description="Binary prompt-injection classifier trained to mitigate over-defense.",
        display_name="PIGuard",
        categories=frozenset({GuardrailCategory.PROMPT_INJECTION}),
        primary_category=GuardrailCategory.PROMPT_INJECTION,
        stages=frozenset({GuardrailStage.INPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.SCORE}),
        backend=BackendType.LOCAL_ENCODER,
        vendor="leolee99",
        default_license="mit",
    ),
    GuardrailName.JASPER: GuardrailMetadata(
        description="Binary prompt-injection classifiers.",
        display_name="Jasper",
        categories=frozenset({GuardrailCategory.PROMPT_INJECTION}),
        primary_category=GuardrailCategory.PROMPT_INJECTION,
        stages=frozenset({GuardrailStage.INPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.SCORE}),
        backend=BackendType.LOCAL_ENCODER,
        vendor="JasperLS",
        default_license="mit",
    ),
    GuardrailName.OFFTOPIC: GuardrailMetadata(
        description="Cross-encoder relevance detector that flags whether an input strays from a comparison text.",
        display_name="Off-Topic",
        categories=frozenset({GuardrailCategory.OFF_TOPIC}),
        primary_category=GuardrailCategory.OFF_TOPIC,
        stages=frozenset({GuardrailStage.INPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.SCORE}),
        backend=BackendType.LOCAL_ENCODER,
        required_validate_kwargs=frozenset({"comparison_text"}),
        vendor="GovTech Singapore",
        default_license="mit",
    ),
    GuardrailName.OPENAI_MODERATION: GuardrailMetadata(
        description="Hosted moderation API flagging content across 13 harm categories with calibrated scores.",
        display_name="OpenAI Moderation",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY, GuardrailCategory.TOXICITY}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.MULTI_LABEL, OutputShape.SCORE}),
        backend=BackendType.HOSTED_API,
        requires_api_key=True,
        multilingual=True,
        multimodal=True,
        vendor="OpenAI",
        default_license="proprietary",
    ),
    GuardrailName.PANGOLIN: GuardrailMetadata(
        description="Binary prompt-injection classifier.",
        display_name="Pangolin Guard",
        categories=frozenset({GuardrailCategory.PROMPT_INJECTION}),
        primary_category=GuardrailCategory.PROMPT_INJECTION,
        stages=frozenset({GuardrailStage.INPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.SCORE}),
        backend=BackendType.LOCAL_ENCODER,
        vendor="dcarpintero",
        default_license="apache-2.0",
    ),
    GuardrailName.PROTECTAI: GuardrailMetadata(
        description="Binary prompt-injection classifiers.",
        display_name="ProtectAI",
        categories=frozenset({GuardrailCategory.PROMPT_INJECTION}),
        primary_category=GuardrailCategory.PROMPT_INJECTION,
        stages=frozenset({GuardrailStage.INPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.SCORE}),
        backend=BackendType.LOCAL_ENCODER,
        vendor="ProtectAI",
        default_license="apache-2.0",
    ),
    GuardrailName.SENTINEL: GuardrailMetadata(
        description="Binary prompt-injection classifier.",
        display_name="Sentinel",
        categories=frozenset({GuardrailCategory.PROMPT_INJECTION}),
        primary_category=GuardrailCategory.PROMPT_INJECTION,
        stages=frozenset({GuardrailStage.INPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.SCORE}),
        backend=BackendType.LOCAL_ENCODER,
        vendor="Qualifire",
        # Gated on HuggingFace and released under Elastic License 2.0; redistribution not cleared.
        default_license="elastic-2.0",
    ),
    GuardrailName.SHIELD_GEMMA: GuardrailMetadata(
        description="Policy-conditioned safety classifier that judges a prompt against a user-supplied policy via Yes/No token logits.",
        display_name="ShieldGemma",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.SCORE}),
        backend=BackendType.LOCAL_DECODER,
        vendor="Google",
        default_license="gemma",
    ),
    GuardrailName.LLAMA_GUARD: GuardrailMetadata(
        description="Decoder-LLM safety classifier judging prompts and responses against the 14-category MLCommons hazard taxonomy.",
        display_name="Llama Guard",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.CATEGORICAL}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        multilingual=True,
        multimodal=True,
        vendor="Meta",
        # Default is Llama-Guard-3-1B (Llama 3.2); the 8B and 4-12B variants carry different Llama terms.
        default_license="llama-3.2",
        variant_licenses=(
            VariantLicense(model_id="meta-llama/Llama-Guard-3-1B", license="llama-3.2"),
            VariantLicense(model_id="meta-llama/Llama-Guard-3-8B", license="llama-3.1"),
            VariantLicense(model_id="meta-llama/Llama-Guard-4-12B", license="llama-4"),
        ),
    ),
    GuardrailName.AZURE_CONTENT_SAFETY: GuardrailMetadata(
        description="Hosted moderation of text and images across hate, sexual, self-harm, and violence categories with 0-7 severity scores.",
        display_name="Azure Content Safety",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY, GuardrailCategory.TOXICITY}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.MULTI_LABEL, OutputShape.SCORE}),
        backend=BackendType.HOSTED_API,
        requires_api_key=True,
        multilingual=True,
        multimodal=True,
        vendor="Microsoft",
        default_license="proprietary",
    ),
    GuardrailName.AZURE_PROMPT_SHIELDS: GuardrailMetadata(
        description="Hosted detector for direct (user prompt) and indirect (document-borne) prompt-injection and jailbreak attacks.",
        display_name="Azure Prompt Shields",
        categories=frozenset({GuardrailCategory.PROMPT_INJECTION}),
        primary_category=GuardrailCategory.PROMPT_INJECTION,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.RAG_CONTEXT}),
        output_shapes=frozenset({OutputShape.BINARY}),
        backend=BackendType.HOSTED_API,
        optional_validate_kwargs=frozenset({"documents"}),
        requires_api_key=True,
        multilingual=True,
        vendor="Microsoft",
        default_license="proprietary",
    ),
    GuardrailName.ALINIA: GuardrailMetadata(
        description="Hosted content-moderation and safety-detection API with configurable detection policies.",
        display_name="Alinia",
        categories=frozenset(
            {
                GuardrailCategory.CONTENT_SAFETY,
                GuardrailCategory.TOXICITY,
                GuardrailCategory.PII,
                GuardrailCategory.HALLUCINATION,
                GuardrailCategory.PROMPT_INJECTION,
            }
        ),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT, GuardrailStage.RAG_CONTEXT}),
        output_shapes=frozenset({OutputShape.MULTI_LABEL, OutputShape.SCORE}),
        backend=BackendType.HOSTED_API,
        optional_validate_kwargs=frozenset({"context_documents", "output"}),
        requires_api_key=True,
        multilingual=True,
        vendor="Alinia AI",
        default_license="proprietary",
    ),
    GuardrailName.LAKERA_GUARD: GuardrailMetadata(
        description="Hosted API for prompt-injection, jailbreak, content-moderation, and PII detection.",
        display_name="Lakera Guard",
        categories=frozenset(
            {GuardrailCategory.PROMPT_INJECTION, GuardrailCategory.CONTENT_SAFETY, GuardrailCategory.PII}
        ),
        primary_category=GuardrailCategory.PROMPT_INJECTION,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.CATEGORICAL}),
        backend=BackendType.HOSTED_API,
        requires_api_key=True,
        multilingual=True,
        vendor="Lakera",
        default_license="proprietary",
    ),
    GuardrailName.PROMPT_GUARD: GuardrailMetadata(
        description="Encoder classifier for prompt-injection and jailbreak detection.",
        display_name="Prompt Guard 2",
        categories=frozenset({GuardrailCategory.PROMPT_INJECTION}),
        primary_category=GuardrailCategory.PROMPT_INJECTION,
        stages=frozenset({GuardrailStage.INPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.SCORE}),
        backend=BackendType.LOCAL_ENCODER,
        multilingual=True,
        vendor="Meta",
        default_license="llama-4",
    ),
    GuardrailName.BIELIK_GUARD: GuardrailMetadata(
        description="Polish multi-label safety classifier.",
        display_name="Bielik Guard",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY, GuardrailCategory.TOXICITY}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.MULTI_LABEL, OutputShape.SCORE}),
        backend=BackendType.LOCAL_ENCODER,
        multilingual=True,
        vendor="SpeakLeash / Bielik.AI",
        default_license="apache-2.0",
    ),
    GuardrailName.WILD_GUARD: GuardrailMetadata(
        description="One-pass safety-moderation judge reporting prompt harm, response harm, and refusal.",
        display_name="WildGuard",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.CATEGORICAL}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        vendor="Allen Institute for AI",
        default_license="apache-2.0",
    ),
    GuardrailName.DYNA_GUARD: GuardrailMetadata(
        description="Dynamic guardian model evaluating conversation compliance with user-defined policies.",
        display_name="DynaGuard",
        categories=frozenset({GuardrailCategory.GENERAL_JUDGE, GuardrailCategory.CONTENT_SAFETY}),
        primary_category=GuardrailCategory.GENERAL_JUDGE,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.BINARY}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        vendor="DynaGuard",
        default_license="apache-2.0",
    ),
    GuardrailName.NEMOTRON_CONTENT_SAFETY: GuardrailMetadata(
        description="Reasoning safety classifier covering a 22-category content-safety taxonomy.",
        display_name="Nemotron Content Safety",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.CATEGORICAL}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        vendor="NVIDIA",
        # Fine-tune of google/gemma-3-4b-it: NVIDIA Open Model License + Gemma Terms of Use both apply;
        # Gemma is the binding constraint for redistribution.
        default_license="gemma",
    ),
    GuardrailName.POLY_GUARD: GuardrailMetadata(
        description="Multilingual safety-moderation judge reporting request harm, response harm, and refusal across 17 languages.",
        display_name="PolyGuard",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.CATEGORICAL}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        multilingual=True,
        vendor="ToxicityPrompts",
        # Default is PolyGuard-Ministral, under the non-commercial Mistral Research License (MRL);
        # only the Qwen variants are Apache-2.0.
        default_license="mrl",
        variant_licenses=(
            VariantLicense(model_id="ToxicityPrompts/PolyGuard-Ministral", license="mrl"),
            VariantLicense(model_id="ToxicityPrompts/PolyGuard-Qwen", license="apache-2.0"),
            VariantLicense(model_id="ToxicityPrompts/PolyGuard-Qwen-Smol", license="apache-2.0"),
        ),
    ),
    GuardrailName.KANANA_SAFEGUARD: GuardrailMetadata(
        description="Korean safety decoder models covering harmful content, legal risk, and prompt attacks.",
        display_name="Kanana Safeguard",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY, GuardrailCategory.PROMPT_INJECTION}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.CATEGORICAL}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        multilingual=True,
        vendor="Kakao",
        default_license="apache-2.0",
    ),
    GuardrailName.GPT_OSS_SAFEGUARD: GuardrailMetadata(
        description="Policy-grounded reasoning safety classifier that judges text against a bring-your-own written policy.",
        display_name="gpt-oss-safeguard",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY, GuardrailCategory.GENERAL_JUDGE}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT}),
        output_shapes=frozenset({OutputShape.BINARY}),
        backend=BackendType.LOCAL_DECODER,
        vendor="OpenAI",
        default_license="apache-2.0",
    ),
    GuardrailName.PROMETHEUS: GuardrailMetadata(
        description="Open rubric-based LLM judge grading a response on a user-defined 1-5 rubric.",
        display_name="Prometheus",
        categories=frozenset({GuardrailCategory.GENERAL_JUDGE}),
        primary_category=GuardrailCategory.GENERAL_JUDGE,
        stages=frozenset({GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.RUBRIC}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        vendor="KAIST / prometheus-eval",
        # v2 (default) is Apache-2.0 (Mistral base); the v1 checkpoints carry Llama 2 terms.
        default_license="apache-2.0",
        variant_licenses=(
            VariantLicense(model_id="prometheus-eval/prometheus-7b-v2.0", license="apache-2.0"),
            VariantLicense(model_id="prometheus-eval/prometheus-8x7b-v2.0", license="apache-2.0"),
            VariantLicense(model_id="prometheus-eval/prometheus-7b-v1.0", license="llama-2"),
            VariantLicense(model_id="prometheus-eval/prometheus-13b-v1.0", license="llama-2"),
        ),
    ),
    GuardrailName.COMPASS_JUDGER: GuardrailMetadata(
        description="Generalist LLM judge that scores a response against user-defined criteria and rubric on a 1-10 scale.",
        display_name="CompassJudger",
        categories=frozenset({GuardrailCategory.GENERAL_JUDGE}),
        primary_category=GuardrailCategory.GENERAL_JUDGE,
        stages=frozenset({GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.RUBRIC}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        vendor="OpenCompass",
        default_license="apache-2.0",
    ),
    GuardrailName.SELENE: GuardrailMetadata(
        description="General-purpose LLM judge grading a response against a user-defined 1-5 rubric.",
        display_name="Selene 1 Mini",
        categories=frozenset({GuardrailCategory.GENERAL_JUDGE}),
        primary_category=GuardrailCategory.GENERAL_JUDGE,
        stages=frozenset({GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.RUBRIC}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        vendor="Atla",
        # apache-2.0 tag is a base carryover; the Llama-3.1-8B base governs.
        default_license="llama-3.1",
    ),
    GuardrailName.LETTUCE_DETECT: GuardrailMetadata(
        description="Token/span-level RAG hallucination detector.",
        display_name="LettuceDetect",
        categories=frozenset({GuardrailCategory.HALLUCINATION}),
        primary_category=GuardrailCategory.HALLUCINATION,
        stages=frozenset({GuardrailStage.OUTPUT, GuardrailStage.RAG_CONTEXT}),
        output_shapes=frozenset({OutputShape.SPAN, OutputShape.BINARY}),
        backend=BackendType.LIBRARY_WRAPPED,
        required_validate_kwargs=frozenset({"context"}),
        optional_validate_kwargs=frozenset({"question"}),
        vendor="KRLabs",
        default_license="mit",
    ),
    GuardrailName.GLI_GUARD: GuardrailMetadata(
        description="Schema-driven safety, toxicity, jailbreak, and refusal detector.",
        display_name="GLiGuard",
        categories=frozenset(
            {GuardrailCategory.CONTENT_SAFETY, GuardrailCategory.TOXICITY, GuardrailCategory.PROMPT_INJECTION}
        ),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT}),
        output_shapes=frozenset({OutputShape.MULTI_LABEL, OutputShape.CATEGORICAL}),
        backend=BackendType.LIBRARY_WRAPPED,
        vendor="Fastino",
        default_license="apache-2.0",
    ),
    GuardrailName.WATSONX_GUARDIAN: GuardrailMetadata(
        description="Hosted text-detection moderation API running configurable Granite Guardian detectors.",
        display_name="watsonx Guardian",
        categories=frozenset(
            {
                GuardrailCategory.CONTENT_SAFETY,
                GuardrailCategory.BIAS,
                GuardrailCategory.TOXICITY,
                GuardrailCategory.PROMPT_INJECTION,
                GuardrailCategory.HALLUCINATION,
            }
        ),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT, GuardrailStage.RAG_CONTEXT}),
        output_shapes=frozenset({OutputShape.MULTI_LABEL, OutputShape.SPAN}),
        backend=BackendType.HOSTED_API,
        requires_api_key=True,
        vendor="IBM",
        default_license="proprietary",
    ),
    GuardrailName.PATRONUS: GuardrailMetadata(
        description="Hosted evaluation API running configurable evaluators for hallucination, toxicity, PII, prompt injection, and custom judging.",
        display_name="Patronus",
        categories=frozenset(
            {
                GuardrailCategory.GENERAL_JUDGE,
                GuardrailCategory.HALLUCINATION,
                GuardrailCategory.TOXICITY,
                GuardrailCategory.PII,
                GuardrailCategory.PROMPT_INJECTION,
            }
        ),
        primary_category=GuardrailCategory.GENERAL_JUDGE,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT, GuardrailStage.RAG_CONTEXT}),
        output_shapes=frozenset({OutputShape.CATEGORICAL, OutputShape.SCORE}),
        backend=BackendType.HOSTED_API,
        optional_validate_kwargs=frozenset({"output_text", "retrieved_context"}),
        requires_api_key=True,
        vendor="Patronus AI",
        default_license="proprietary",
    ),
    GuardrailName.QWEN3_GUARD: GuardrailMetadata(
        description="Generative safety moderation with three-level severity across 119 languages.",
        display_name="Qwen3Guard",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.CATEGORICAL, OutputShape.SCORE}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        multilingual=True,
        vendor="Qwen",
        default_license="apache-2.0",
    ),
    GuardrailName.QWEN3_GUARD_STREAM: GuardrailMetadata(
        description="Token-level streaming safety moderation with span output.",
        display_name="Qwen3Guard-Stream",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.CATEGORICAL, OutputShape.SPAN}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        multilingual=True,
        vendor="Qwen",
        default_license="apache-2.0",
    ),
}
