"""Central, import-free registry of guardrail capability metadata.

This module is the single source of truth for guardrail taxonomy queries. It
imports only :mod:`any_guardrail.base` (for ``GuardrailName``) and
:mod:`any_guardrail.taxonomy` (leaf enums + model) — never a guardrail
implementation — so filtering/grouping never pulls in ``torch``/``transformers``
or spins up a backend. Each guardrail class mirrors its entry here as
``METADATA``; a parity test enforces that every ``GuardrailName`` has exactly one
entry and that the class ClassVar is that entry.

The ``description`` of each entry equals the guardrail class docstring's first
summary line (also test-enforced), so it doubles as the catalog flavor text.
"""

from any_guardrail.base import GuardrailName
from any_guardrail.taxonomy import (
    BackendType,
    GuardrailCategory,
    GuardrailMetadata,
    GuardrailStage,
    OutputShape,
)

GUARDRAIL_METADATA: dict[GuardrailName, GuardrailMetadata] = {
    GuardrailName.ANYLLM: GuardrailMetadata(
        description="AnyLlm — policy-based LLM judge that grades text against a natural-language policy using any LLM provider supported by any-llm.",
        display_name="AnyLlm",
        categories=frozenset({GuardrailCategory.GENERAL_JUDGE}),
        primary_category=GuardrailCategory.GENERAL_JUDGE,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.SCORE}),
        backend=BackendType.HOSTED_API,
        required_validate_kwargs=frozenset({"policy"}),
        optional_validate_kwargs=frozenset({"model_id", "system_prompt"}),
        requires_api_key=True,
        vendor="Mozilla AI",
        default_license="apache-2.0",
    ),
    GuardrailName.BEDROCK_GUARDRAILS: GuardrailMetadata(
        description="AWS Bedrock Guardrails — hosted, configurable moderation via the ApplyGuardrail API covering content filters, denied topics, PII, word filters, and contextual grounding (Amazon).",
        display_name="Bedrock Guardrails",
        categories=frozenset(
            {
                GuardrailCategory.CONTENT_SAFETY,
                GuardrailCategory.PII,
                GuardrailCategory.OFF_TOPIC,
                GuardrailCategory.HALLUCINATION,
            }
        ),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT, GuardrailStage.RAG_CONTEXT}),
        output_shapes=frozenset({OutputShape.CATEGORICAL}),
        backend=BackendType.HOSTED_API,
        requires_api_key=True,
        multilingual=True,
        vendor="Amazon",
        default_license="proprietary",
    ),
    GuardrailName.DEEPSET: GuardrailMetadata(
        description="Deepset — binary prompt-injection classifier built on DeBERTa-v3-base (deepset).",
        display_name="Deepset",
        categories=frozenset({GuardrailCategory.PROMPT_INJECTION}),
        primary_category=GuardrailCategory.PROMPT_INJECTION,
        stages=frozenset({GuardrailStage.INPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.SCORE}),
        backend=BackendType.LOCAL_ENCODER,
        vendor="deepset",
        default_license="cc-by-4.0",
    ),
    GuardrailName.DUOGUARD: GuardrailMetadata(
        description="DuoGuard — multilingual multi-label safety classifier scoring text across 12 harm categories including jailbreak prompts.",
        display_name="DuoGuard",
        categories=frozenset(
            {GuardrailCategory.CONTENT_SAFETY, GuardrailCategory.TOXICITY, GuardrailCategory.PROMPT_INJECTION}
        ),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.MULTI_LABEL, OutputShape.SCORE}),
        backend=BackendType.LOCAL_ENCODER,
        multilingual=True,
        vendor="DuoGuard",
        default_license="apache-2.0",
    ),
    GuardrailName.FLOWJUDGE: GuardrailMetadata(
        description="Flow Judge — local LLM judge scoring text against user-defined criteria, metrics, and rubrics via the flow-judge library (Flow AI).",
        display_name="Flow Judge",
        categories=frozenset({GuardrailCategory.GENERAL_JUDGE}),
        primary_category=GuardrailCategory.GENERAL_JUDGE,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.RUBRIC}),
        backend=BackendType.LIBRARY_WRAPPED,
        required_validate_kwargs=frozenset({"output"}),
        vendor="Flow AI",
        default_license="apache-2.0",
    ),
    GuardrailName.GLIDER: GuardrailMetadata(
        description="GLIDER — prompt-based LLM judge that grades text against user-supplied pass criteria and rubric, returning reasoning and highlighted phrases (Patronus AI).",
        display_name="GLIDER",
        categories=frozenset({GuardrailCategory.GENERAL_JUDGE}),
        primary_category=GuardrailCategory.GENERAL_JUDGE,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.RUBRIC}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        vendor="Patronus AI",
        default_license="cc-by-nc-4.0",
    ),
    GuardrailName.GRANITE_GUARDIAN: GuardrailMetadata(
        description="Granite Guardian — hybrid-thinking safety and judge model covering harm, RAG groundedness, and function-calling risks via bring-your-own-criteria (IBM).",
        display_name="Granite Guardian",
        categories=frozenset(
            {
                GuardrailCategory.CONTENT_SAFETY,
                GuardrailCategory.HALLUCINATION,
                GuardrailCategory.BIAS,
                GuardrailCategory.TOOL_USE,
                GuardrailCategory.GENERAL_JUDGE,
                GuardrailCategory.PROMPT_INJECTION,
            }
        ),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT, GuardrailStage.RAG_CONTEXT}),
        output_shapes=frozenset({OutputShape.CATEGORICAL, OutputShape.SCORE}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"available_tools", "documents", "output_text"}),
        vendor="IBM",
        default_license="apache-2.0",
    ),
    GuardrailName.HARMGUARD: GuardrailMetadata(
        description="HarmAug-Guard — binary safety and jailbreak classifier built on DeBERTa-v3-large, scoring a prompt or prompt-response pair.",
        display_name="HarmAug-Guard",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY, GuardrailCategory.PROMPT_INJECTION}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.SCORE}),
        backend=BackendType.LOCAL_ENCODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        vendor="hbseong",
        default_license="apache-2.0",
    ),
    GuardrailName.INJECGUARD: GuardrailMetadata(
        description="PIGuard — binary prompt-injection classifier built on DeBERTa-v3 and trained to mitigate over-defense (successor to InjecGuard).",
        display_name="PIGuard",
        categories=frozenset({GuardrailCategory.PROMPT_INJECTION}),
        primary_category=GuardrailCategory.PROMPT_INJECTION,
        stages=frozenset({GuardrailStage.INPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.SCORE}),
        backend=BackendType.LOCAL_ENCODER,
        vendor="leolee99",
        default_license="mit",
    ),
    GuardrailName.JASPER: GuardrailMetadata(
        description="Jasper — binary prompt-injection classifiers built on DeBERTa-v3-base and gELECTRA-base (JasperLS).",
        display_name="Jasper",
        categories=frozenset({GuardrailCategory.PROMPT_INJECTION}),
        primary_category=GuardrailCategory.PROMPT_INJECTION,
        stages=frozenset({GuardrailStage.INPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.SCORE}),
        backend=BackendType.LOCAL_ENCODER,
        vendor="JasperLS",
        default_license="mit",
    ),
    GuardrailName.OFFTOPIC: GuardrailMetadata(
        description="Off-Topic — cross-encoder relevance detector that flags whether an input strays from a comparison text (GovTech Singapore).",
        display_name="Off-Topic",
        categories=frozenset({GuardrailCategory.OFF_TOPIC}),
        primary_category=GuardrailCategory.OFF_TOPIC,
        stages=frozenset({GuardrailStage.INPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.SCORE}),
        backend=BackendType.LOCAL_ENCODER,
        required_validate_kwargs=frozenset({"comparison_text"}),
        vendor="GovTech Singapore",
        default_license="mit",
    ),
    GuardrailName.OPENAI_MODERATION: GuardrailMetadata(
        description="OpenAI Moderation — hosted moderation API flagging content across 13 harm categories with calibrated scores (OpenAI).",
        display_name="OpenAI Moderation",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY, GuardrailCategory.TOXICITY}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.MULTI_LABEL, OutputShape.SCORE}),
        backend=BackendType.HOSTED_API,
        requires_api_key=True,
        multilingual=True,
        multimodal=True,
        vendor="OpenAI",
        default_license="proprietary",
    ),
    GuardrailName.PANGOLIN: GuardrailMetadata(
        description="Pangolin Guard — binary prompt-injection classifier built on ModernBERT (dcarpintero).",
        display_name="Pangolin Guard",
        categories=frozenset({GuardrailCategory.PROMPT_INJECTION}),
        primary_category=GuardrailCategory.PROMPT_INJECTION,
        stages=frozenset({GuardrailStage.INPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.SCORE}),
        backend=BackendType.LOCAL_ENCODER,
        vendor="dcarpintero",
        default_license="apache-2.0",
    ),
    GuardrailName.PROTECTAI: GuardrailMetadata(
        description="ProtectAI — binary prompt-injection classifiers built on DeBERTa-v3 and DistilRoBERTa (ProtectAI).",
        display_name="ProtectAI",
        categories=frozenset({GuardrailCategory.PROMPT_INJECTION}),
        primary_category=GuardrailCategory.PROMPT_INJECTION,
        stages=frozenset({GuardrailStage.INPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.SCORE}),
        backend=BackendType.LOCAL_ENCODER,
        vendor="ProtectAI",
        default_license="apache-2.0",
    ),
    GuardrailName.SENTINEL: GuardrailMetadata(
        description="Sentinel — binary prompt-injection classifier built on DeBERTa (Qualifire).",
        display_name="Sentinel",
        categories=frozenset({GuardrailCategory.PROMPT_INJECTION}),
        primary_category=GuardrailCategory.PROMPT_INJECTION,
        stages=frozenset({GuardrailStage.INPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.SCORE}),
        backend=BackendType.LOCAL_ENCODER,
        vendor="Qualifire",
        default_license="apache-2.0",
    ),
    GuardrailName.SHIELD_GEMMA: GuardrailMetadata(
        description="ShieldGemma — policy-conditioned safety classifier that judges a prompt against a user-supplied policy via Yes/No token logits (Google).",
        display_name="ShieldGemma",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.SCORE}),
        backend=BackendType.LOCAL_DECODER,
        vendor="Google",
        default_license="gemma",
    ),
    GuardrailName.LLAMA_GUARD: GuardrailMetadata(
        description="Llama Guard — decoder-LLM safety classifier judging prompts and responses against the 14-category MLCommons hazard taxonomy (Meta).",
        display_name="Llama Guard",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.CATEGORICAL}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        multilingual=True,
        multimodal=True,
        vendor="Meta",
        default_license="llama-3.1",
    ),
    GuardrailName.AZURE_CONTENT_SAFETY: GuardrailMetadata(
        description="Azure AI Content Safety — hosted moderation of text and images across hate, sexual, self-harm, and violence categories with 0-7 severity scores (Microsoft).",
        display_name="Azure Content Safety",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY, GuardrailCategory.TOXICITY}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.MULTI_LABEL, OutputShape.SCORE}),
        backend=BackendType.HOSTED_API,
        requires_api_key=True,
        multilingual=True,
        multimodal=True,
        vendor="Microsoft",
        default_license="proprietary",
    ),
    GuardrailName.AZURE_PROMPT_SHIELDS: GuardrailMetadata(
        description="Azure AI Prompt Shields — hosted detector for direct (user prompt) and indirect (document-borne) prompt-injection and jailbreak attacks (Microsoft).",
        display_name="Azure Prompt Shields",
        categories=frozenset({GuardrailCategory.PROMPT_INJECTION}),
        primary_category=GuardrailCategory.PROMPT_INJECTION,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.RAG_CONTEXT}),
        output_shapes=frozenset({OutputShape.BINARY}),
        backend=BackendType.HOSTED_API,
        optional_validate_kwargs=frozenset({"documents"}),
        requires_api_key=True,
        multilingual=True,
        vendor="Microsoft",
        default_license="proprietary",
    ),
    GuardrailName.ALINIA: GuardrailMetadata(
        description="Alinia — hosted content-moderation and safety-detection API with configurable detection policies (Alinia AI).",
        display_name="Alinia",
        categories=frozenset(
            {
                GuardrailCategory.CONTENT_SAFETY,
                GuardrailCategory.TOXICITY,
                GuardrailCategory.PII,
                GuardrailCategory.HALLUCINATION,
            }
        ),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT, GuardrailStage.RAG_CONTEXT}),
        output_shapes=frozenset({OutputShape.MULTI_LABEL, OutputShape.SCORE}),
        backend=BackendType.HOSTED_API,
        optional_validate_kwargs=frozenset({"context_documents", "output"}),
        requires_api_key=True,
        multilingual=True,
        vendor="Alinia AI",
        default_license="proprietary",
    ),
    GuardrailName.LAKERA_GUARD: GuardrailMetadata(
        description="Lakera Guard — hosted API for prompt-injection, jailbreak, content-moderation, and PII detection (Lakera).",
        display_name="Lakera Guard",
        categories=frozenset(
            {GuardrailCategory.PROMPT_INJECTION, GuardrailCategory.CONTENT_SAFETY, GuardrailCategory.PII}
        ),
        primary_category=GuardrailCategory.PROMPT_INJECTION,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.CATEGORICAL}),
        backend=BackendType.HOSTED_API,
        requires_api_key=True,
        multilingual=True,
        vendor="Lakera",
        default_license="proprietary",
    ),
    GuardrailName.PROMPT_GUARD: GuardrailMetadata(
        description="Prompt Guard 2 — encoder classifier for prompt-injection and jailbreak detection (Meta).",
        display_name="Prompt Guard 2",
        categories=frozenset({GuardrailCategory.PROMPT_INJECTION}),
        primary_category=GuardrailCategory.PROMPT_INJECTION,
        stages=frozenset({GuardrailStage.INPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.SCORE}),
        backend=BackendType.LOCAL_ENCODER,
        multilingual=True,
        vendor="Meta",
        default_license="llama-4",
    ),
    GuardrailName.BIELIK_GUARD: GuardrailMetadata(
        description="Bielik Guard — Polish multi-label safety classifier (SpeakLeash / Bielik.AI).",
        display_name="Bielik Guard",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY, GuardrailCategory.TOXICITY}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.MULTI_LABEL, OutputShape.SCORE}),
        backend=BackendType.LOCAL_ENCODER,
        multilingual=True,
        vendor="SpeakLeash / Bielik.AI",
        default_license="apache-2.0",
    ),
    GuardrailName.WILD_GUARD: GuardrailMetadata(
        description="WildGuard — one-pass safety-moderation judge reporting prompt harm, response harm, and refusal (Allen Institute for AI).",
        display_name="WildGuard",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.BINARY, OutputShape.CATEGORICAL}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        vendor="Allen Institute for AI",
        default_license="apache-2.0",
    ),
    GuardrailName.DYNA_GUARD: GuardrailMetadata(
        description="DynaGuard — dynamic guardian model evaluating conversation compliance with user-defined policies.",
        display_name="DynaGuard",
        categories=frozenset({GuardrailCategory.GENERAL_JUDGE, GuardrailCategory.CONTENT_SAFETY}),
        primary_category=GuardrailCategory.GENERAL_JUDGE,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.BINARY}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        vendor="DynaGuard",
        default_license="apache-2.0",
    ),
    GuardrailName.NEMOTRON_CONTENT_SAFETY: GuardrailMetadata(
        description="Nemotron Content Safety — 4B reasoning safety classifier covering a 22-category content-safety taxonomy (NVIDIA).",
        display_name="Nemotron Content Safety",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.CATEGORICAL}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        vendor="NVIDIA",
        default_license="nvidia-open-model",
    ),
    GuardrailName.POLY_GUARD: GuardrailMetadata(
        description="PolyGuard — multilingual safety-moderation judge reporting request harm, response harm, and refusal across 17 languages.",
        display_name="PolyGuard",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.CATEGORICAL}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        multilingual=True,
        vendor="ToxicityPrompts",
        default_license="apache-2.0",
    ),
    GuardrailName.KANANA_SAFEGUARD: GuardrailMetadata(
        description="Kanana Safeguard — Korean safety decoder models covering harmful content, legal risk, and prompt attacks (Kakao).",
        display_name="Kanana Safeguard",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY, GuardrailCategory.PROMPT_INJECTION}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.CATEGORICAL}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        multilingual=True,
        vendor="Kakao",
        default_license="apache-2.0",
    ),
    GuardrailName.GPT_OSS_SAFEGUARD: GuardrailMetadata(
        description="gpt-oss-safeguard — policy-grounded reasoning safety classifier that judges text against a bring-your-own written policy (OpenAI).",
        display_name="gpt-oss-safeguard",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY, GuardrailCategory.GENERAL_JUDGE}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT}),
        output_shapes=frozenset({OutputShape.BINARY}),
        backend=BackendType.LOCAL_DECODER,
        vendor="OpenAI",
        default_license="apache-2.0",
    ),
    GuardrailName.PROMETHEUS: GuardrailMetadata(
        description="Prometheus — open rubric-based LLM judge grading a response on a user-defined 1-5 rubric (KAIST / prometheus-eval).",
        display_name="Prometheus",
        categories=frozenset({GuardrailCategory.GENERAL_JUDGE}),
        primary_category=GuardrailCategory.GENERAL_JUDGE,
        stages=frozenset({GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.RUBRIC}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        vendor="KAIST / prometheus-eval",
        default_license="apache-2.0",
    ),
    GuardrailName.COMPASS_JUDGER: GuardrailMetadata(
        description="CompassJudger — generalist LLM judge that scores a response against user-defined criteria and rubric on a 1-10 scale (OpenCompass).",
        display_name="CompassJudger",
        categories=frozenset({GuardrailCategory.GENERAL_JUDGE}),
        primary_category=GuardrailCategory.GENERAL_JUDGE,
        stages=frozenset({GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.RUBRIC}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        vendor="OpenCompass",
        default_license="apache-2.0",
    ),
    GuardrailName.SELENE: GuardrailMetadata(
        description="Selene 1 Mini — general-purpose LLM judge grading a response against a user-defined 1-5 rubric (Atla).",
        display_name="Selene 1 Mini",
        categories=frozenset({GuardrailCategory.GENERAL_JUDGE}),
        primary_category=GuardrailCategory.GENERAL_JUDGE,
        stages=frozenset({GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.RUBRIC}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        vendor="Atla",
        default_license="apache-2.0",
    ),
    GuardrailName.LETTUCE_DETECT: GuardrailMetadata(
        description="LettuceDetect — token/span-level RAG hallucination detector built on ModernBERT (KRLabs).",
        display_name="LettuceDetect",
        categories=frozenset({GuardrailCategory.HALLUCINATION}),
        primary_category=GuardrailCategory.HALLUCINATION,
        stages=frozenset({GuardrailStage.OUTPUT, GuardrailStage.RAG_CONTEXT}),
        output_shapes=frozenset({OutputShape.SPAN, OutputShape.BINARY}),
        backend=BackendType.LIBRARY_WRAPPED,
        required_validate_kwargs=frozenset({"context"}),
        optional_validate_kwargs=frozenset({"question"}),
        vendor="KRLabs",
        default_license="mit",
    ),
    GuardrailName.GLI_GUARD: GuardrailMetadata(
        description="GLiGuard — schema-driven safety, toxicity, jailbreak, and refusal detector built on GLiNER2 (Fastino).",
        display_name="GLiGuard",
        categories=frozenset(
            {GuardrailCategory.CONTENT_SAFETY, GuardrailCategory.TOXICITY, GuardrailCategory.PROMPT_INJECTION}
        ),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT}),
        output_shapes=frozenset({OutputShape.MULTI_LABEL, OutputShape.CATEGORICAL}),
        backend=BackendType.LIBRARY_WRAPPED,
        vendor="Fastino",
        default_license="apache-2.0",
    ),
    GuardrailName.WATSONX_GUARDIAN: GuardrailMetadata(
        description="watsonx Guardian — hosted text-detection moderation API running configurable Granite Guardian detectors (IBM).",
        display_name="watsonx Guardian",
        categories=frozenset(
            {
                GuardrailCategory.CONTENT_SAFETY,
                GuardrailCategory.BIAS,
                GuardrailCategory.TOXICITY,
                GuardrailCategory.PROMPT_INJECTION,
                GuardrailCategory.HALLUCINATION,
            }
        ),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT, GuardrailStage.RAG_CONTEXT}),
        output_shapes=frozenset({OutputShape.MULTI_LABEL, OutputShape.SPAN}),
        backend=BackendType.HOSTED_API,
        requires_api_key=True,
        vendor="IBM",
        default_license="proprietary",
    ),
    GuardrailName.PATRONUS: GuardrailMetadata(
        description="Patronus — hosted evaluation API running configurable evaluators for hallucination, toxicity, PII, prompt injection, and custom judging (Patronus AI).",
        display_name="Patronus",
        categories=frozenset(
            {
                GuardrailCategory.HALLUCINATION,
                GuardrailCategory.GENERAL_JUDGE,
                GuardrailCategory.TOXICITY,
                GuardrailCategory.PII,
                GuardrailCategory.PROMPT_INJECTION,
            }
        ),
        primary_category=GuardrailCategory.HALLUCINATION,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT, GuardrailStage.RAG_CONTEXT}),
        output_shapes=frozenset({OutputShape.CATEGORICAL, OutputShape.SCORE}),
        backend=BackendType.HOSTED_API,
        optional_validate_kwargs=frozenset({"output_text", "retrieved_context"}),
        requires_api_key=True,
        vendor="Patronus AI",
        default_license="proprietary",
    ),
    GuardrailName.QWEN3_GUARD: GuardrailMetadata(
        description="Qwen3Guard-Gen — generative safety moderation with three-level severity across 119 languages (Qwen).",
        display_name="Qwen3Guard",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.CATEGORICAL, OutputShape.SCORE}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        multilingual=True,
        vendor="Qwen",
        default_license="apache-2.0",
    ),
    GuardrailName.QWEN3_GUARD_STREAM: GuardrailMetadata(
        description="Qwen3Guard-Stream — token-level streaming safety moderation with span output (Qwen).",
        display_name="Qwen3Guard-Stream",
        categories=frozenset({GuardrailCategory.CONTENT_SAFETY}),
        primary_category=GuardrailCategory.CONTENT_SAFETY,
        stages=frozenset({GuardrailStage.INPUT, GuardrailStage.OUTPUT}),
        output_shapes=frozenset({OutputShape.CATEGORICAL, OutputShape.SPAN}),
        backend=BackendType.LOCAL_DECODER,
        optional_validate_kwargs=frozenset({"output_text"}),
        multilingual=True,
        vendor="Qwen",
        default_license="apache-2.0",
    ),
}
